language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mkharchenko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mkharchenko/docker-react npm run test